### ISSUE TITLE
Lint eror during compile

### ISSUE THREAD

**Issue by jugendhacker** [calliope-edu/Calliope-Android-App#6]
I'm currently trying to build the latest version inside the F-Droid build setup and get the following error during the build:

```
> Task :app:lintVitalRelease FAILED                                                                                                                                           
/home/vagrant/build/cc.calliope.mini/app/src/main/res/layout-land/activity_select_editor.xml:53: Error: @+id/divider is not a sibling in the same ConstraintLayout [NotSibling
]                                         
        app:layout_constraintTop_toBottomOf="@+id/divider" />
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                    
/home/vagrant/build/cc.calliope.mini/app/src/main/res/layout/device_item.xml:69: Error: @id/pattern is not a sibling in the same ConstraintLayout [NotSibling]
   android:layout_toRightOf="@id/pattern"                                                                                                                                     
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                              
   Explanation for issues of type "NotSibling":
   Layout constraints in a given ConstraintLayout or RelativeLayout should
   reference other views within the same relative layout (but not itself!)
                                           
2 errors, 0 warnings   
```

I am actually not sure what causes it, but maybe you could help me debugging it?

**Comment by Amerlander** [comment]
Would you try again with the master branch? I fixed the layout constraints and it should work now.
If it does I'll create a new version release 1.1.2

**Comment by jugendhacker** [comment]
It does build based on Amerlander/Calliope-Android-App@0446fd4daa3c6944f144f796a359f48e274eed3f so feel free to release it.

**Comment by Amerlander** [comment]
Released: https://github.com/calliope-edu/Calliope-Android-App/releases/tag/1.1.2

Thank your for your feedback and your help!

**Comment by jugendhacker** [comment]
@Amerlander sorry but seems like your tag does not contain Amerlander/Calliope-Android-App@0446fd4daa3c6944f144f796a359f48e274eed3f , so build still fails when building from the `1.1.2` tag.

**Comment by Amerlander** [comment]
Yes, sorry! I mixed it up with the other repository. Here it is: https://github.com/calliope-edu/Calliope-Android-App/releases/tag/1.1.2.1
